config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('job.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.homepage, name="home"),
    path('accounts/login/', views.user_login, name='login'),
    path('accounts/signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('likespage/', views.likespage, name='likespage'),    
    path('createjob/', views.Createjob.as_view(), name='createjob'),
    path('detail/<int:id>/', views.detail, name='detail'),
    
]

job/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField(max_length=100)
    def __str__(self):
        return self.title
    
class Viloyat(models.Model):
    title = models.CharField(max_length=100)
    def __str__(self):
        return self.title


class Job(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    pricemin = models.IntegerField()
    pricemax = models.IntegerField()
    manzil = models.CharField(max_length=200)
    phoneNumber =models.CharField(max_length=12)
    category5 = models.ForeignKey(Category,on_delete=models.CASCADE)
    viloyat5 = models.ForeignKey(Viloyat,on_delete=models.CASCADE)
    time = models.DateField(auto_now_add=True)
    counter = models.CharField(max_length=200,blank=True)
    def __str__(self):
        return self.title

class Apply_job(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    manzil = models.CharField(max_length=200)
    phoneNumber =models.CharField(max_length=9)
    img = models.ImageField(upload_to='apply/')
    categ = models.ForeignKey(Job,on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Message(models.Model):
    name = models.CharField(max_length=20)
    body = models.CharField(max_length=200)
    img = models.ImageField(upload_to='messages/')
    rating = models.IntegerField()
    def __str__(self):
        return self.name

job/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Userename'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password1'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password2'}))
    class Meta:
        model = User 
        fields = ['username','password1','password2']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

job/views.py
from .models import Job,Viloyat,Category,Apply_job,Message
from .filters import UserFilter
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout 
from .forms import UserCreationForm, LoginForm
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin


def homepage(request):
    user_list = Job.objects.all().order_by('-id')
    viloyat =  Viloyat.objects.all()
    category =  Category.objects.all()
    user_filter =   UserFilter(request.GET, queryset=user_list)
   

    data = 'home'
    messages = Message.objects.all().order_by('-id')
    if request.method == 'POST':
        Message.objects.create(
        body=request.POST.get('body'),
        name=request.POST.get('name'),
        rating= request.POST.get('rating'),
        img= request.FILES.get('img55')
    )
        return redirect('/')

    return render(request, 'index.html',
{ 'user_filter1':user_filter, 'data':data, 'list':user_list , 'viloyat':viloyat,'category':category ,'messages':messages}
)

def likespage(request):
    data = 'lekis'
    
    user_list = Job.objects.all().order_by('-id')
    return render(request, 'job-list.html',{'posts':user_list,'data':data})


class Createjob(LoginRequiredMixin , CreateView):
    model = Job
    fields = ['title','body','pricemin','pricemax','manzil','phoneNumber','category5','viloyat5',]

    template_name = "about.html"
    success_url = '/'
    
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    

def detail(request,id):
    job = Job.objects.get(id=id)

    applys = job.apply_job_set.all().order_by('-id')
    viloyatlar = Viloyat.objects.all()
    job.counter = applys.count()
    job.save()
    if request.method == 'POST':

        Apply_job.objects.create(
        categ=job,
        body=request.POST.get('body'),
        title=request.POST.get('title'),
        phoneNumber=request.POST.get('phoneNumber'),
        manzil=request.POST.get('manzil'),
        img= request.FILES.get('img'),
     
    )
        print(job.counter)


        return redirect('detail',id=job.id)


    return render(request,'job-detail.html',{'job':job,'applys':applys ,'viloyatlar':viloyatlar})


    
    

def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)    
                return redirect('home')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})




def user_logout(request):
    logout(request)
    return redirect('home')

templates/about.html
{% extends 'link.html' %}

{% block content %}
        <!-- Header End -->
        <div class="container-xxl py-5 bg-dark page-header mb-5">
            <div class="container my-1 pt-2 pb-2">
                <h1 class="display-3 text-white mb-3 animated slideInDown">Job qoshish</h1>
            </div>
        </div>
        <!-- Header End -->

<center>


<form  action="" method="POST">
{% csrf_token %}

{% for x in form %}
    <div style="width: 300px; margin: 5px 0;">{{x}}</div>
{% endfor %}
    

<input id="checbtn" style="width: 300px !important;" placeholder="" class="btn btn-danger" type="submit">

</form>
</center><br><br>
<style>
    #id_body{
        resize: none;
    }
</style>
<script>
    
addEventListener("input",()=>{
    if (Number( document.getElementById('id_pricemax').value) > Number( document.getElementById('id_pricemin').value)) {
    document.getElementById('checbtn').removeAttribute('disabled')
    }else{
    document.getElementById('checbtn').setAttribute('disabled','')
    }

})

document.getElementById('id_title').setAttribute('class','form-control w-100')
document.getElementById('id_title').setAttribute('placeholder','Ish nomi')
document.getElementById('id_body').setAttribute('class','form-control w-100')
document.getElementById('id_body').setAttribute('placeholder','Ish haqida batafsil')
document.getElementById('id_pricemin').setAttribute('class','form-control w-100')
document.getElementById('id_pricemin').setAttribute('placeholder','Boshlangich narh $')
document.getElementById('id_pricemax').setAttribute('class','form-control w-100')
document.getElementById('id_pricemax').setAttribute('placeholder','Oxirgi narh Katta bolsin $')
document.getElementById('id_manzil').setAttribute('class','form-control w-100')
document.getElementById('id_manzil').setAttribute('placeholder','Manzil')
document.getElementById('id_phoneNumber').setAttribute('class','form-control w-100')
document.getElementById('id_phoneNumber').setAttribute('placeholder','Telefon raqam')
document.getElementById('id_category5').setAttribute('class','form-select w-100')
document.getElementById('id_category5').children[0].innerHTML = 'Category'
document.getElementById('id_viloyat5').setAttribute('class','form-select w-100')
document.getElementById('id_viloyat5').children[0].innerHTML = 'Viloyat'


</script>




    {% endblock content %}

templates/job-detail.html
{% extends 'link.html' %}

{% block content %}

<style>
    #saveli i{
        font-size: 40px !important;

    }
</style>

        <!-- Header End -->
        <div class="container-xxl py-5 bg-dark page-header mb-5">
            <div class="container my-5 pt-5 pb-4">
                <h1 class="display-3 text-white mb-3 animated slideInDown">Job Detail</h1>
               <div class="d-flex align-items-center">
                <div id="saveli" > </div>
               <button class="btn btn-warning" onclick="navigator.clipboard.writeText(location.href);">Copy</button>
            </div>
            </div>
        </div>
        <!-- Header End -->
    
        

       

        <!-- Job Detail Start -->
        <div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
            <div class="container">
                <div class="row gy-5 gx-4">
                    <div class="col-lg-8">
                        <div class="d-flex align-items-center mb-5">
                            <div class="text-start">
                                <h3 class="mb-3 d-flex align-items-center gap-1">    {{job.title}}  </h3>
                                <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>{{job.manzil}}</span>
                                <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i> {{job.time}}</span>
                                <span class="text-truncate me-3"><i class="far fa-money-bill-alt text-primary me-2"></i>${{job.pricemin}} - ${{job.pricemax}}</span>
                                <span class="text-truncate me-0"><i class="fa fa-phone text-primary me-2"></i>{{job.phoneNumber}}</span>
                                
                            </div>
                        </div>

                        <div class="mb-5">
                            <h4 class="mb-3">Ish Haqida</h4>
                            <p>{{job.body}}</p>
                
                            
                        </div>
        
                        <div class="">
                            <h4 class="mb-4">Ishga ariza tashlash</h4>

                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row g-3">
                                    <div class="col-12 col-sm-6">
                                        <input maxlength="18"   minlength="4" required  type="text" id="title" class="form-control"  name="title" placeholder="Familya va Ismingiz">
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <input required oninput="if(this.value.length > 12){this.value = this.value.slice(0,12)}  "  type="number" maxlength="9" name="phoneNumber" class="form-control" placeholder="Telefon raqamingiz">
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <input  required  type="text" maxlength="20" minlength="6" placeholder="Manzilingiz" name="manzil" class="form-control bg-white">
                                    </div>                                    
                                    <div style="position: relative;" class="col-12 col-sm-6">
                                    <input id="imginput" oninput="document.getElementById('valuethis').innerHTML = this.value "  required type="file"  style="opacity: 0; width:0.1px !important; height: 0.1px !important; position: absolute ; top: 0; left: 30px;" placeholder="Ismi" accept="image/*" name="img" class="form-control bg-white">
                                   <div class="d-flex align-items-center gap-1">
                                       <label style="width: 50%;" class="btn btn-primary" for="imginput">Rasmingiz</label>
                                       <div  id="valuethis"></div>
                                </div>
                                    </div>
                                    <div class="col-12">
                                        <textarea minlength="15" maxlength="100"  required class="form-control" rows="5" name="body" placeholder="Coverletter"></textarea>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

<div class="col-lg-4">


    
    {% if applys|length == 0  %}
    <center><h2>Ariza tashlaganlar xozrcha yoq</h2></center>
    {% else %}
        
<center><h2>Ariza tashlaganlar     {{applys|length}}-ta</h2></center>
{% endif %}
<div  style="max-height: 600px; overflow-y: scroll; overflow-x: hidden;">
    {% for x in applys %}
    <div class="bg-light " style=" padding: 5px 2px 4px 10px;" >
        <img style=" width: 90%  ; " src="/media/{{x.img}}" alt="">
        <h4 style="word-wrap: break-word; text-wrap: wrap !important;" class="mb-2 mt-2">{{x.title}}</h4>
        <div style="word-wrap:break-word !important; text-wrap:wrap !important;"  class="mb-2 d-flex align-items-center"><i class="fa fa-map-marker-alt text-primary me-2"></i> {{x.manzil}}</div>
        <div style="word-wrap:break-word !important; text-wrap:wrap !important;" class="mb-2 d-flex align-items-center"><i class="fa fa-phone text-primary me-2"></i>{{x.phoneNumber}}</div>
        <div style="word-wrap:break-word !important; text-wrap:wrap !important;"  class="mb-2 d-flex align-items-center"><i class="far fa-clock text-primary me-2"></i> {{x.time}}</div>
        <p class="m-0" style="word-wrap: break-word;">{{x.body}}</p>
    </div><div class="py-1 bg-primary"></div>
    
       
    {% endfor %}

</div>
</div>



    </div>
    </div>
    </div>
    <script >
        if (localStorage.getItem('like{{job.id}}') == '{{job.id}}')  {
            document.getElementById('saveli').innerHTML = `<i class="fa fa-heart text-danger me-2"></i>`
        }else{
            document.getElementById('saveli').innerHTML = `<i onclick="localStorage.setItem('like{{job.id}}','{{job.id}}')" class="fa fa-heart text-dark me-2"></i>`
            
        }
        addEventListener("click",()=>{
            if (localStorage.getItem('like{{job.id}}') == '{{job.id}}')  {
            document.getElementById('saveli').innerHTML = `<i class="fa fa-heart text-danger me-2"></i>`
        }else{
            document.getElementById('saveli').innerHTML = `<i onclick="localStorage.setItem('like{{job.id}}','{{job.id}}')" class="fa fa-heart text-dark me-2"></i>`
            
        }
        })
    </script>
        <!-- Job Detail End -->


        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Company</h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Quick Links</h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Contact</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Rewa, Madhya Pradesh, IND</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+91199919199</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@ajaykumar.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Newsletter</h5>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved. 
							
							<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
							Designed By <a class="border-bottom" href="">Code By Ajay Kumar</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    {% endblock content %}

templates/job-list.html
{% extends 'link.html' %}
{% block content %}
<script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/list.pagination.js/0.1.1/list.pagination.min.js"></script>



        <!-- Header End -->
        <div class="container-xxl py-5 bg-dark page-header mb-5">
            <div class="container my-5 pt-5 pb-4">
                <h1 class="display-3 text-white mb-3 animated slideInDown">Sevimli ishlar</h1>

            </div>
        </div>
        <!-- Header End -->


        <div style="display: flex; flex-direction: column-reverse; gap: 10px;" id="test-list">
            <div  class="pagination" style="display: flex ;  justify-content: center; gap: 15px;"></div> 
         <div class="list">
            {% for user in posts %}

        <div class="name">
                <div id="rom{{user.id}}" class="job-item p-4 mb-2 border border-1 border-primary  " style="border-radius: 10px; margin-left: 3%; margin-right: 3%;">
                <div class="row g-4">
                    <div class="col-sm-12 col-md-8 d-flex align-items-center">
                        <div class="text-start">
                            <h5 class="mb-3" style="text-transform: capitalize;">{{ user.title }}</h5>
                            <div class="d-flex gap-1 flex-wrap">
                            <div style="word-wrap:break-word !important; text-wrap:wrap;"  class="text-truncate me-3 "><i class="fa fa-map-marker-alt text-primary me-2"></i>{{user.viloyat5}}, {{user.manzil}}</div>
                            <div style="word-wrap:break-word !important; text-wrap:wrap;"  class="text-truncate me-3 "><i class="fa fa-list-alt text-primary me-1" aria-hidden="true"></i>  {{user.category5}}</div>
                            <div style="word-wrap:break-word !important; text-wrap:wrap;"  class="text-truncate me-3 "><i class="far fa-money-bill-alt text-primary me-2"></i>${{user.pricemin}} - ${{user.pricemax}}</div>
                            <div style="word-wrap:break-word !important; text-wrap:wrap;"  class="text-truncate me-0 "><i class="far fa-calendar-alt text-primary me-2"></i> {{user.time}}</div>
                        </div>
    
                        </div>
                    </div>
    
                    <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                        <div class="d-flex flex-wrap align-items-center gap-2 mb-3">
                             <i onclick="localStorage.removeItem('like{{user.id}}'), location.reload()" style="font-size: 25px;" class="fa fa-trash text-danger" aria-hidden="true"></i>
                            <a style="position: relative;" class="btn btn-primary" href="/detail/{{user.id}}/"> Apply Now 
                                <div style="width: 30px; border-radius: 10px; font-size: smaller; height: 30px;display: flex;justify-content: center; align-items: center; background-color: #ffc107; position: absolute; top: -25px; right: -10px;" class=" text-truncate text-dark">
                            {% if user.counter|length == 0  %}
                                0
                             {% else %}
                             {{user.counter}}
                             {% endif %}
                             
                            </div>
                            </a>
                        </div>
    
                    </div>
    
                </div>
                </div>
          </div>

            {% endfor %}
        </div>
      </div>


        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Company</h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Quick Links</h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Contact</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Rewa, Madhya Pradesh, IND</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+91199919199</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@ajaykumar.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Newsletter</h5>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved. 
							
							<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
							Designed By <a class="border-bottom" href="">Code By Ajay Kumar</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <style>
           .pagination .active a{
                background-color: #ffc107 !important;
                border: 2px solid #ffc107;
                color: black;
            }
        </style>

        <!-- Back to Top -->
        <a href="#" style="display: block !important; " class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
<script>


setInterval(() => {
   
    if( document.querySelector('.list').children.length == 0){
        document.querySelector('.list').innerHTML = `<center><h2>Sizga yoqgan Ish mavjud emas</h2></center>`
    }else{

    }

}, 500);



'{% for i in posts %}'
if(localStorage.getItem('like{{i.id}}') == '{{i.id}}'){
        document.getElementById('rom{{i.id}}')

     }else{
   document.getElementById('rom{{i.id}}').parentElement.remove()
}
'{% endfor %}'

var monkeyList = new List('test-list', 
{
  valueNames: ['name'],
  page: 10,
  pagination: [{
      paginationClass: "pagination",
      outerWindow: 1,
    }
]


}
)







for (const iterator of document.querySelector('.pagination').children) {

iterator.children[0].setAttribute('class','btn btn-primary panigbutton')

}

addEventListener("click",()=>{
    
for (const iterator of document.querySelector('.pagination').children) {
  
  iterator.children[0].setAttribute('class','btn btn-primary panigbutton')

}
})

</script>





    {% endblock content %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <title>Login</title>
</head>
<body>
 
   
<center>

    <h1>Login</h1>
<form method="POST">
    {% csrf_token %}

    {% for x in form %}
       
        <div >  <div class=" text-primary"> {{x.label}} </div> {{x}}</div>
    {% endfor %}
        
<br>
    <button type="submit" class="btn btn-primary">Login</button>
    <a href="{% url 'signup' %}">Dont have Account Create</a>
</form>
</center>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <title>Login</title>
</head>
<body>
 <center>


    <h1>Signup</h1>
    <form method="POST">
        {% csrf_token %}
        {% for x in form %}
        {{x.label}} <br>
        {{x}} <br>
        {% endfor %} <br>
        <button class="btn btn-warning" type="submit">Signup</button>
        <a href="{% url 'login' %}">Already have account?</a>
    </form>
 </center>
</body>
</html>